apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-presentation
  name: kubernetes-presentation-svc-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kubernetes-presentation
  type: LoadBalancer
